addons:
  apt:
    packages:
      - chef
      - git
      - graphviz
      - libarchive-dev
    sources:
      - chef-stable-trusty
cache:
  - apt
  - bundler
dist: trusty
language: ruby
branches:
  only:
    - master
install:  travis_wait bundle install --without changelog --jobs 7 --retry=3
before_script:
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
  - git config --global user.email "ci@berkshelf.com"
  - git config --global user.name "Berkshelf"
matrix:
  include:
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: ruby-head
    - rvm: 2.6.5
      before_install:
        - gem update --system
        - rm Gemfile.lock
    - rvm: 2.6.5
      env:
        CHEFSTYLE: 1
      script: bundle exec rake style
    - rvm: 2.6.5
      before_install:
        # Needed until https://github.com/travis-ci/apt-package-whitelist/pull/1820 is merged
        - sudo apt-get update
        - sudo apt-get -y install squid3 apache2-utils
        - sudo htpasswd -b -c /etc/squid3/passwords proxy proxy
      sudo: required
      env:
        - PROXY_TESTS_DIR=/tmp/proxy_tests
        - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo
        - CHEF_LICENSE="accept-no-persist"
        - rvmsudo_secure_path=1
      script:
        - git clone https://github.com/chef/proxy_tests.git
        - cd proxy_tests && bundle exec chef-client -z -o proxy_tests::render && cd ..
        - rvmsudo -E bundle exec bash $PROXY_TESTS_DIR/run_tests.sh berkshelf \* \* /tmp/out.txt
      after_script: cat /tmp/out.txt
  allow_failures:
    - rvm: ruby-head

script: bundle exec thor spec:ci
